// wrapFortranBindings.h
// This file is generated by Shroud 0.14.0. Do not edit.
/**
 * \file wrapFortranBindings.h
 * \brief Shroud generated wrapper for FortranBindings library
 */
// For C users and C++ implementation

#ifndef WRAPFORTRANBINDINGS_H
#define WRAPFORTRANBINDINGS_H

#ifdef __cplusplus
#include <cstddef>
#include <cstdint>
#else
#include <stddef.h>
#include <stdint.h>
#endif
#include "typesFortranBindings.h"

// splicer begin CXX_declarations
// splicer end CXX_declarations

#ifdef __cplusplus
extern "C" {
#endif

// splicer begin C_declarations
// splicer end C_declarations

void FOR_initImmersedEq_d_i32(size_t gridHeight, size_t gridWidth,
    size_t gridDepth, size_t fSize, size_t nnzMaxB, double *p,
    double *f, double deltaX, double deltaY, double deltaZ, double dt,
    double tolerance, size_t maxBCGIterations);

void FOR_initImmersedEq_s_i32(size_t gridHeight, size_t gridWidth,
    size_t gridDepth, size_t fSize, size_t nnzMaxB, float *p, float *f,
    double deltaX, double deltaY, double deltaZ, double dt,
    double tolerance, size_t maxBCGIterations);

void FOR_initImmersedEq_d_i64(size_t gridHeight, size_t gridWidth,
    size_t gridDepth, size_t fSize, size_t nnzMaxB, double *p,
    double *f, double deltaX, double deltaY, double deltaZ, double dt,
    double tolerance, size_t maxBCGIterations);

void FOR_initImmersedEq_s_i64(size_t gridHeight, size_t gridWidth,
    size_t gridDepth, size_t fSize, size_t nnzMaxB, float *p, float *f,
    double deltaX, double deltaY, double deltaZ, double dt,
    double tolerance, size_t maxBCGIterations);

void FOR_solveImmersedEq_d_i32(double *result, size_t nnzB,
    int32_t *rowOffsetsB, int32_t *colIndsB, double *valuesB);

void FOR_solveImmersedEq_s_i32(float *result, size_t nnzB,
    int32_t *rowOffsetsB, int32_t *colIndsB, float *valuesB);

void FOR_solveImmersedEq_d_i64(double *result, size_t nnzB,
    int64_t *rowOffsetsB, int64_t *colIndsB, double *valuesB);

void FOR_solveImmersedEq_s_i64(float *result, size_t nnzB,
    int64_t *rowOffsetsB, int64_t *colIndsB, float *valuesB);

void FOR_solveImmersedEqPrimes_d_i32(double *resultPPrime,
    double *resultFPrime, size_t nnzB, int32_t *rowOffsetsB,
    int32_t *colIndsB, double *valuesB, size_t nnzR,
    int32_t *colOffsetsR, int32_t *rowIndsR, double *valuesR,
    double *UGamma, double *uStar);

void FOR_solveImmersedEqPrimes_s_i32(float *resultPPrime,
    float *resultFPrime, size_t nnzB, int32_t *rowOffsetsB,
    int32_t *colIndsB, float *valuesB, size_t nnzR,
    int32_t *colOffsetsR, int32_t *rowIndsR, float *valuesR,
    float *UGamma, float *uStar);

void FOR_solveImmersedEqPrimes_d_i64(double *resultPPrime,
    double *resultFPrime, size_t nnzB, int64_t *rowOffsetsB,
    int64_t *colIndsB, double *valuesB, size_t nnzR,
    int64_t *colOffsetsR, int64_t *rowIndsR, double *valuesR,
    double *UGamma, double *uStar);

void FOR_solveImmersedEqPrimes_s_i64(float *resultPPrime,
    float *resultFPrime, size_t nnzB, int64_t *rowOffsetsB,
    int64_t *colIndsB, float *valuesB, size_t nnzR,
    int64_t *colOffsetsR, int64_t *rowIndsR, float *valuesR,
    float *UGamma, float *uStar);

void FOR_finalizeImmersedEq_d_i32(void);

void FOR_finalizeImmersedEq_s_i32(void);

void FOR_finalizeImmersedEq_d_i64(void);

void FOR_finalizeImmersedEq_s_i64(void);

#ifdef __cplusplus
}
#endif

#endif  // WRAPFORTRANBINDINGS_H
