// utilpoisson_gpu.cpp
// This file is generated by Shroud 0.14.0. Do not edit.

#include "typespoisson_gpu.h"


#ifdef __cplusplus
extern "C" {
#endif

// Release library allocated memory.
void POI_SHROUD_memory_destructor(POI_SHROUD_capsule_data *cap)
{
    cap->addr = nullptr;
    cap->idtor = 0;  // avoid deleting again
    cap->cmemflags = cap->cmemflags & ~SWIG_MEM_OWN;
}

#ifdef __cplusplus
}
#endif
