// wrapEigenBCGSolver_eigen.cpp
// This file is generated by Shroud 0.14.0. Do not edit.

#include "wrapper/FortranBindings.hpp"
#include "wrapEigenBCGSolver_eigen.h"

// splicer begin namespace.eigen.CXX_definitions
// splicer end namespace.eigen.CXX_definitions

extern "C" {

// splicer begin namespace.eigen.C_definitions
// splicer end namespace.eigen.C_definitions

size_t EIG_eigen_initEigenDecomp_d(size_t dim1Length, size_t dim2Length,
    size_t dim3Length, const double *dim1Delta, const double *dim2Delta,
    const double *dim3Delta, int dim1SegType, int dim2SegType,
    int dim3SegType, bool dim1StartIsNeumann, bool dim1EndIsNeumann,
    bool dim2StartIsNeumann, bool dim2EndIsNeumann,
    bool dim3StartIsNeumann, bool dim3EndIsNeumann, double dim1StartVal,
    double dim1EndVal, double dim2StartVal, double dim2EndVal,
    double dim3StartVal, double dim3EndVal, bool thomas,
    double helmholtzShift)
{
    // splicer begin namespace.eigen.function.initEigenDecomp_d
    size_t SHC_rv = eigen::initEigenDecomp_d(dim1Length, dim2Length,
        dim3Length, dim1Delta, dim2Delta, dim3Delta, dim1SegType,
        dim2SegType, dim3SegType, dim1StartIsNeumann, dim1EndIsNeumann,
        dim2StartIsNeumann, dim2EndIsNeumann, dim3StartIsNeumann,
        dim3EndIsNeumann, dim1StartVal, dim1EndVal, dim2StartVal,
        dim2EndVal, dim3StartVal, dim3EndVal, thomas, helmholtzShift);
    return SHC_rv;
    // splicer end namespace.eigen.function.initEigenDecomp_d
}

size_t EIG_eigen_initEigenDecomp_s(size_t dim1Length, size_t dim2Length,
    size_t dim3Length, const float *dim1Delta, const float *dim2Delta,
    const float *dim3Delta, int dim1SegType, int dim2SegType,
    int dim3SegType, bool dim1StartIsNeumann, bool dim1EndIsNeumann,
    bool dim2StartIsNeumann, bool dim2EndIsNeumann,
    bool dim3StartIsNeumann, bool dim3EndIsNeumann, float dim1StartVal,
    float dim1EndVal, float dim2StartVal, float dim2EndVal,
    float dim3StartVal, float dim3EndVal, bool thomas,
    float helmholtzShift)
{
    // splicer begin namespace.eigen.function.initEigenDecomp_s
    size_t SHC_rv = eigen::initEigenDecomp_s(dim1Length, dim2Length,
        dim3Length, dim1Delta, dim2Delta, dim3Delta, dim1SegType,
        dim2SegType, dim3SegType, dim1StartIsNeumann, dim1EndIsNeumann,
        dim2StartIsNeumann, dim2EndIsNeumann, dim3StartIsNeumann,
        dim3EndIsNeumann, dim1StartVal, dim1EndVal, dim2StartVal,
        dim2EndVal, dim3StartVal, dim3EndVal, thomas, helmholtzShift);
    return SHC_rv;
    // splicer end namespace.eigen.function.initEigenDecomp_s
}

void EIG_eigen_solveEigenDecomp_d(size_t solverHandle, double *x,
    double *b)
{
    // splicer begin namespace.eigen.function.solveEigenDecomp_d
    eigen::solveEigenDecomp_d(solverHandle, x, b);
    // splicer end namespace.eigen.function.solveEigenDecomp_d
}

void EIG_eigen_solveEigenDecomp_s(size_t solverHandle, float *x,
    float *b)
{
    // splicer begin namespace.eigen.function.solveEigenDecomp_s
    eigen::solveEigenDecomp_s(solverHandle, x, b);
    // splicer end namespace.eigen.function.solveEigenDecomp_s
}

void EIG_eigen_synch_d(size_t solverHandle)
{
    // splicer begin namespace.eigen.function.synch_d
    eigen::synch_d(solverHandle);
    // splicer end namespace.eigen.function.synch_d
}

void EIG_eigen_synch_s(size_t solverHandle)
{
    // splicer begin namespace.eigen.function.synch_s
    eigen::synch_s(solverHandle);
    // splicer end namespace.eigen.function.synch_s
}

void EIG_eigen_finalizeEigenDecomp(void)
{
    // splicer begin namespace.eigen.function.finalizeEigenDecomp
    eigen::finalizeEigenDecomp();
    // splicer end namespace.eigen.function.finalizeEigenDecomp
}

}  // extern "C"
