// wrapEigenBCGSolver_eigen.h
// This file is generated by Shroud 0.14.0. Do not edit.
/**
 * \file wrapEigenBCGSolver_eigen.h
 * \brief Shroud generated wrapper for eigen namespace
 */
// For C users and C++ implementation

#ifndef WRAPEIGENBCGSOLVER_EIGEN_H
#define WRAPEIGENBCGSOLVER_EIGEN_H

#ifdef __cplusplus
#include <cstddef>
#else
#include <stddef.h>
#include <stdbool.h>
#endif
#include "typesEigenBCGSolver.h"

// splicer begin namespace.eigen.CXX_declarations
// splicer end namespace.eigen.CXX_declarations

#ifdef __cplusplus
extern "C" {
#endif

// splicer begin namespace.eigen.C_declarations
// splicer end namespace.eigen.C_declarations

size_t EIG_eigen_initEigenDecomp_d(size_t dim1Length, size_t dim2Length,
    size_t dim3Length, const double *dim1Delta, const double *dim2Delta,
    const double *dim3Delta, int dim1SegType, int dim2SegType,
    int dim3SegType, bool dim1StartIsNeumann, bool dim1EndIsNeumann,
    bool dim2StartIsNeumann, bool dim2EndIsNeumann,
    bool dim3StartIsNeumann, bool dim3EndIsNeumann, double dim1StartVal,
    double dim1EndVal, double dim2StartVal, double dim2EndVal,
    double dim3StartVal, double dim3EndVal, bool thomas,
    double helmholtzShift);

size_t EIG_eigen_initEigenDecomp_s(size_t dim1Length, size_t dim2Length,
    size_t dim3Length, const float *dim1Delta, const float *dim2Delta,
    const float *dim3Delta, int dim1SegType, int dim2SegType,
    int dim3SegType, bool dim1StartIsNeumann, bool dim1EndIsNeumann,
    bool dim2StartIsNeumann, bool dim2EndIsNeumann,
    bool dim3StartIsNeumann, bool dim3EndIsNeumann, float dim1StartVal,
    float dim1EndVal, float dim2StartVal, float dim2EndVal,
    float dim3StartVal, float dim3EndVal, bool thomas,
    float helmholtzShift);

void EIG_eigen_solveEigenDecomp_d(size_t solverHandle, double *x,
    double *b);

void EIG_eigen_solveEigenDecomp_s(size_t solverHandle, float *x,
    float *b);

void EIG_eigen_synch_d(size_t solverHandle);

void EIG_eigen_synch_s(size_t solverHandle);

void EIG_eigen_finalizeEigenDecomp(void);

#ifdef __cplusplus
}
#endif

#endif  // WRAPEIGENBCGSOLVER_EIGEN_H
