// wrapEigenBCGSolver_ImEq.cpp
// This file is generated by Shroud 0.14.0. Do not edit.

#include "wrapper/FortranBindings.hpp"
#include "wrapEigenBCGSolver_ImEq.h"

// splicer begin namespace.ImEq.CXX_definitions
// splicer end namespace.ImEq.CXX_definitions

extern "C" {

// splicer begin namespace.ImEq.C_definitions
// splicer end namespace.ImEq.C_definitions

void EIG_ImEq_initImmersedEq_d_i32(size_t dim1Length, size_t dim2Length,
    size_t dim3Length, bool dim1StartIsNeumann, bool dim1EndIsNeumann,
    bool dim2StartIsNeumann, bool dim2EndIsNeumann,
    bool dim3StartIsNeumann, bool dim3EndIsNeumann, double dim1StartVal,
    double dim1EndVal, double dim2StartVal, double dim2EndVal,
    double dim3StartVal, double dim3EndVal, size_t dim1SegSpacing,
    size_t dim2SegSpacing, size_t dim3SegSpacing, size_t forceSize,
    size_t nnzMax, double *p, double *f, double *dim1Delta,
    double *dim2Delta, double *dim3Delta, double dt,
    bool dim1UniformDelta, bool dim2UniformDelta, bool dim3UniformDelta,
    double tol, size_t maxIterations)
{
    // splicer begin namespace.ImEq.function.initImmersedEq_d_i32
    ImEq::initImmersedEq_d_i32(dim1Length, dim2Length, dim3Length,
        dim1StartIsNeumann, dim1EndIsNeumann, dim2StartIsNeumann,
        dim2EndIsNeumann, dim3StartIsNeumann, dim3EndIsNeumann,
        dim1StartVal, dim1EndVal, dim2StartVal, dim2EndVal,
        dim3StartVal, dim3EndVal, dim1SegSpacing, dim2SegSpacing,
        dim3SegSpacing, forceSize, nnzMax, p, f, dim1Delta, dim2Delta,
        dim3Delta, dt, dim1UniformDelta, dim2UniformDelta,
        dim3UniformDelta, tol, maxIterations);
    // splicer end namespace.ImEq.function.initImmersedEq_d_i32
}

void EIG_ImEq_initImmersedEq_s_i32(size_t dim1Length, size_t dim2Length,
    size_t dim3Length, bool dim1StartIsNeumann, bool dim1EndIsNeumann,
    bool dim2StartIsNeumann, bool dim2EndIsNeumann,
    bool dim3StartIsNeumann, bool dim3EndIsNeumann, double dim1StartVal,
    double dim1EndVal, double dim2StartVal, double dim2EndVal,
    double dim3StartVal, double dim3EndVal, size_t dim1SegSpacing,
    size_t dim2SegSpacing, size_t dim3SegSpacing, size_t forceSize,
    size_t nnzMax, float *p, float *f, float *dim1Delta,
    float *dim2Delta, float *dim3Delta, double dt,
    bool dim1UniformDelta, bool dim2UniformDelta, bool dim3UniformDelta,
    double tol, size_t maxIterations)
{
    // splicer begin namespace.ImEq.function.initImmersedEq_s_i32
    ImEq::initImmersedEq_s_i32(dim1Length, dim2Length, dim3Length,
        dim1StartIsNeumann, dim1EndIsNeumann, dim2StartIsNeumann,
        dim2EndIsNeumann, dim3StartIsNeumann, dim3EndIsNeumann,
        dim1StartVal, dim1EndVal, dim2StartVal, dim2EndVal,
        dim3StartVal, dim3EndVal, dim1SegSpacing, dim2SegSpacing,
        dim3SegSpacing, forceSize, nnzMax, p, f, dim1Delta, dim2Delta,
        dim3Delta, dt, dim1UniformDelta, dim2UniformDelta,
        dim3UniformDelta, tol, maxIterations);
    // splicer end namespace.ImEq.function.initImmersedEq_s_i32
}

void EIG_ImEq_initImmersedEq_d_i64(size_t dim1Length, size_t dim2Length,
    size_t dim3Length, bool dim1StartIsNeumann, bool dim1EndIsNeumann,
    bool dim2StartIsNeumann, bool dim2EndIsNeumann,
    bool dim3StartIsNeumann, bool dim3EndIsNeumann, double dim1StartVal,
    double dim1EndVal, double dim2StartVal, double dim2EndVal,
    double dim3StartVal, double dim3EndVal, size_t dim1SegSpacing,
    size_t dim2SegSpacing, size_t dim3SegSpacing, size_t forceSize,
    size_t nnzMax, double *p, double *f, double *dim1Delta,
    double *dim2Delta, double *dim3Delta, double dt,
    bool dim1UniformDelta, bool dim2UniformDelta, bool dim3UniformDelta,
    double tol, size_t maxIterations)
{
    // splicer begin namespace.ImEq.function.initImmersedEq_d_i64
    ImEq::initImmersedEq_d_i64(dim1Length, dim2Length, dim3Length,
        dim1StartIsNeumann, dim1EndIsNeumann, dim2StartIsNeumann,
        dim2EndIsNeumann, dim3StartIsNeumann, dim3EndIsNeumann,
        dim1StartVal, dim1EndVal, dim2StartVal, dim2EndVal,
        dim3StartVal, dim3EndVal, dim1SegSpacing, dim2SegSpacing,
        dim3SegSpacing, forceSize, nnzMax, p, f, dim1Delta, dim2Delta,
        dim3Delta, dt, dim1UniformDelta, dim2UniformDelta,
        dim3UniformDelta, tol, maxIterations);
    // splicer end namespace.ImEq.function.initImmersedEq_d_i64
}

void EIG_ImEq_initImmersedEq_s_i64(size_t dim1Length, size_t dim2Length,
    size_t dim3Length, bool dim1StartIsNeumann, bool dim1EndIsNeumann,
    bool dim2StartIsNeumann, bool dim2EndIsNeumann,
    bool dim3StartIsNeumann, bool dim3EndIsNeumann, float dim1StartVal,
    float dim1EndVal, float dim2StartVal, float dim2EndVal,
    float dim3StartVal, float dim3EndVal, size_t dim1SegSpacing,
    size_t dim2SegSpacing, size_t dim3SegSpacing, size_t forceSize,
    size_t nnzMax, float *p, float *f, float *dim1Delta,
    float *dim2Delta, float *dim3Delta, double dt,
    bool dim1UniformDelta, bool dim2UniformDelta, bool dim3UniformDelta,
    double tol, size_t maxIterations)
{
    // splicer begin namespace.ImEq.function.initImmersedEq_s_i64
    ImEq::initImmersedEq_s_i64(dim1Length, dim2Length, dim3Length,
        dim1StartIsNeumann, dim1EndIsNeumann, dim2StartIsNeumann,
        dim2EndIsNeumann, dim3StartIsNeumann, dim3EndIsNeumann,
        dim1StartVal, dim1EndVal, dim2StartVal, dim2EndVal,
        dim3StartVal, dim3EndVal, dim1SegSpacing, dim2SegSpacing,
        dim3SegSpacing, forceSize, nnzMax, p, f, dim1Delta, dim2Delta,
        dim3Delta, dt, dim1UniformDelta, dim2UniformDelta,
        dim3UniformDelta, tol, maxIterations);
    // splicer end namespace.ImEq.function.initImmersedEq_s_i64
}

void EIG_ImEq_solveImmersedEq_d_i32_0(double *result, size_t nnzB,
    int32_t *rowOffsetsB, int32_t *colIndsB, double *val)
{
    // splicer begin namespace.ImEq.function.solveImmersedEq_d_i32_0
    ImEq::solveImmersedEq_d_i32(result, nnzB, rowOffsetsB, colIndsB,
        val);
    // splicer end namespace.ImEq.function.solveImmersedEq_d_i32_0
}

void EIG_ImEq_solveImmersedEq_d_i32_1(double *result, size_t nnzB,
    int32_t *rowOffsetsB, int32_t *colIndsB, double *val, bool multi)
{
    // splicer begin namespace.ImEq.function.solveImmersedEq_d_i32_1
    ImEq::solveImmersedEq_d_i32(result, nnzB, rowOffsetsB, colIndsB,
        val, multi);
    // splicer end namespace.ImEq.function.solveImmersedEq_d_i32_1
}

void EIG_ImEq_solveImmersedEq_s_i32_0(float *result, size_t nnzB,
    int32_t *rowOffsetsB, int32_t *colIndsB, float *val)
{
    // splicer begin namespace.ImEq.function.solveImmersedEq_s_i32_0
    ImEq::solveImmersedEq_s_i32(result, nnzB, rowOffsetsB, colIndsB,
        val);
    // splicer end namespace.ImEq.function.solveImmersedEq_s_i32_0
}

void EIG_ImEq_solveImmersedEq_s_i32_1(float *result, size_t nnzB,
    int32_t *rowOffsetsB, int32_t *colIndsB, float *val, bool multi)
{
    // splicer begin namespace.ImEq.function.solveImmersedEq_s_i32_1
    ImEq::solveImmersedEq_s_i32(result, nnzB, rowOffsetsB, colIndsB,
        val, multi);
    // splicer end namespace.ImEq.function.solveImmersedEq_s_i32_1
}

void EIG_ImEq_solveImmersedEq_d_i64_0(double *result, size_t nnzB,
    int64_t *rowOffsetsB, int64_t *colIndsB, double *val)
{
    // splicer begin namespace.ImEq.function.solveImmersedEq_d_i64_0
    ImEq::solveImmersedEq_d_i64(result, nnzB, rowOffsetsB, colIndsB,
        val);
    // splicer end namespace.ImEq.function.solveImmersedEq_d_i64_0
}

void EIG_ImEq_solveImmersedEq_d_i64_1(double *result, size_t nnzB,
    int64_t *rowOffsetsB, int64_t *colIndsB, double *val, bool multi)
{
    // splicer begin namespace.ImEq.function.solveImmersedEq_d_i64_1
    ImEq::solveImmersedEq_d_i64(result, nnzB, rowOffsetsB, colIndsB,
        val, multi);
    // splicer end namespace.ImEq.function.solveImmersedEq_d_i64_1
}

void EIG_ImEq_solveImmersedEq_s_i64_0(float *result, size_t nnzB,
    int64_t *rowOffsetsB, int64_t *colIndsB, float *val)
{
    // splicer begin namespace.ImEq.function.solveImmersedEq_s_i64_0
    ImEq::solveImmersedEq_s_i64(result, nnzB, rowOffsetsB, colIndsB,
        val);
    // splicer end namespace.ImEq.function.solveImmersedEq_s_i64_0
}

void EIG_ImEq_solveImmersedEq_s_i64_1(float *result, size_t nnzB,
    int64_t *rowOffsetsB, int64_t *colIndsB, float *val, bool multi)
{
    // splicer begin namespace.ImEq.function.solveImmersedEq_s_i64_1
    ImEq::solveImmersedEq_s_i64(result, nnzB, rowOffsetsB, colIndsB,
        val, multi);
    // splicer end namespace.ImEq.function.solveImmersedEq_s_i64_1
}

void EIG_ImEq_solveImmersedEqPrimes_d_i32(double *resultPPrime,
    double *resultFPrime, size_t nnzB, int32_t *rowOffsetsB,
    int32_t *colIndsB, double *valuesB, size_t nnzR,
    int32_t *colOffsetsR, int32_t *rowIndsR, double *valuesR,
    double *UGamma, double *uStar)
{
    // splicer begin namespace.ImEq.function.solveImmersedEqPrimes_d_i32
    ImEq::solveImmersedEqPrimes_d_i32(resultPPrime, resultFPrime, nnzB,
        rowOffsetsB, colIndsB, valuesB, nnzR, colOffsetsR, rowIndsR,
        valuesR, UGamma, uStar);
    // splicer end namespace.ImEq.function.solveImmersedEqPrimes_d_i32
}

void EIG_ImEq_solveImmersedEqPrimes_s_i32(float *resultPPrime,
    float *resultFPrime, size_t nnzB, int32_t *rowOffsetsB,
    int32_t *colIndsB, float *valuesB, size_t nnzR,
    int32_t *colOffsetsR, int32_t *rowIndsR, float *valuesR,
    float *UGamma, float *uStar)
{
    // splicer begin namespace.ImEq.function.solveImmersedEqPrimes_s_i32
    ImEq::solveImmersedEqPrimes_s_i32(resultPPrime, resultFPrime, nnzB,
        rowOffsetsB, colIndsB, valuesB, nnzR, colOffsetsR, rowIndsR,
        valuesR, UGamma, uStar);
    // splicer end namespace.ImEq.function.solveImmersedEqPrimes_s_i32
}

void EIG_ImEq_solveImmersedEqPrimes_d_i64(double *resultPPrime,
    double *resultFPrime, size_t nnzB, int64_t *rowOffsetsB,
    int64_t *colIndsB, double *valuesB, size_t nnzR,
    int64_t *colOffsetsR, int64_t *rowIndsR, double *valuesR,
    double *UGamma, double *uStar)
{
    // splicer begin namespace.ImEq.function.solveImmersedEqPrimes_d_i64
    ImEq::solveImmersedEqPrimes_d_i64(resultPPrime, resultFPrime, nnzB,
        rowOffsetsB, colIndsB, valuesB, nnzR, colOffsetsR, rowIndsR,
        valuesR, UGamma, uStar);
    // splicer end namespace.ImEq.function.solveImmersedEqPrimes_d_i64
}

void EIG_ImEq_solveImmersedEqPrimes_s_i64(float *resultPPrime,
    float *resultFPrime, size_t nnzB, int64_t *rowOffsetsB,
    int64_t *colIndsB, float *valuesB, size_t nnzR,
    int64_t *colOffsetsR, int64_t *rowIndsR, float *valuesR,
    float *UGamma, float *uStar)
{
    // splicer begin namespace.ImEq.function.solveImmersedEqPrimes_s_i64
    ImEq::solveImmersedEqPrimes_s_i64(resultPPrime, resultFPrime, nnzB,
        rowOffsetsB, colIndsB, valuesB, nnzR, colOffsetsR, rowIndsR,
        valuesR, UGamma, uStar);
    // splicer end namespace.ImEq.function.solveImmersedEqPrimes_s_i64
}

void EIG_ImEq_finalizeImmersedEq_d_i32(void)
{
    // splicer begin namespace.ImEq.function.finalizeImmersedEq_d_i32
    ImEq::finalizeImmersedEq_d_i32();
    // splicer end namespace.ImEq.function.finalizeImmersedEq_d_i32
}

void EIG_ImEq_finalizeImmersedEq_s_i32(void)
{
    // splicer begin namespace.ImEq.function.finalizeImmersedEq_s_i32
    ImEq::finalizeImmersedEq_s_i32();
    // splicer end namespace.ImEq.function.finalizeImmersedEq_s_i32
}

void EIG_ImEq_finalizeImmersedEq_d_i64(void)
{
    // splicer begin namespace.ImEq.function.finalizeImmersedEq_d_i64
    ImEq::finalizeImmersedEq_d_i64();
    // splicer end namespace.ImEq.function.finalizeImmersedEq_d_i64
}

void EIG_ImEq_finalizeImmersedEq_s_i64(void)
{
    // splicer begin namespace.ImEq.function.finalizeImmersedEq_s_i64
    ImEq::finalizeImmersedEq_s_i64();
    // splicer end namespace.ImEq.function.finalizeImmersedEq_s_i64
}

}  // extern "C"
