// wrapFortranBindings.h
// This file is generated by Shroud 0.14.0. Do not edit.
/**
 * \file wrapFortranBindings.h
 * \brief Shroud generated wrapper for FortranBindings library
 */
// For C users and C++ implementation

#ifndef WRAPFORTRANBINDINGS_H
#define WRAPFORTRANBINDINGS_H

#ifdef __cplusplus
#include <cstddef>
#include <cstdint>
#else
#include <stddef.h>
#include <stdint.h>
#include <stdbool.h>
#endif
#include "typesFortranBindings.h"

// splicer begin CXX_declarations
// splicer end CXX_declarations

#ifdef __cplusplus
extern "C" {
#endif

// splicer begin C_declarations
// splicer end C_declarations

void FOR_initImmersedEq_0(const size_t height, const size_t width,
    const size_t depth, const size_t fSize, const size_t nnzMaxB,
    float *p, float *f, const double deltaX, const double deltaY,
    const double deltaZ, const double tolerance,
    const size_t maxBCGIterations);

void FOR_initImmersedEq_1(const size_t height, const size_t width,
    const size_t depth, const size_t fSize, const size_t nnzMaxB,
    float *p, float *f, const double deltaX, const double deltaY,
    const double deltaZ, const double tolerance,
    const size_t maxBCGIterations);

void FOR_initImmersedEq_2(const size_t height, const size_t width,
    const size_t depth, const size_t fSize, const size_t nnzMaxB,
    double *p, double *f, const double deltaX, const double deltaY,
    const double deltaZ, const double tolerance,
    const size_t maxBCGIterations);

void FOR_initImmersedEq_3(const size_t height, const size_t width,
    const size_t depth, const size_t fSize, const size_t nnzMaxB,
    double *p, double *f, const double deltaX, const double deltaY,
    const double deltaZ, const double tolerance,
    const size_t maxBCGIterations);

void FOR_solveImmersedEq(===>result c_prototype<===, size_t nnzB,
    ===>rowPointersB c_prototype<===, ===>colPointersB c_prototype<===,
    ===>valuesB c_prototype<===);

void FOR_solveImmersedEq_bufferify(===>result c_prototype<===,
    size_t nnzB, ===>rowPointersB c_prototype<===,
    ===>colPointersB c_prototype<===, ===>valuesB c_prototype<===);

void FOR_solveImmersedEq_0(float *result, size_t nnzB,
    int32_t *rowPointersB, int32_t *colPointersB, float *valuesB,
    bool multiStream);

void FOR_solveImmersedEq_1(float *result, size_t nnzB,
    int64_t *rowPointersB, int64_t *colPointersB, float *valuesB,
    bool multiStream);

void FOR_solveImmersedEq_2(double *result, size_t nnzB,
    int32_t *rowPointersB, int32_t *colPointersB, double *valuesB,
    bool multiStream);

void FOR_solveImmersedEq_3(double *result, size_t nnzB,
    int64_t *rowPointersB, int64_t *colPointersB, double *valuesB,
    bool multiStream);

#ifdef __cplusplus
}
#endif

#endif  // WRAPFORTRANBINDINGS_H
