! wrapfEigenBCGSolver_eigen.f
! This file is generated by Shroud 0.14.0. Do not edit.
!>
!! \file wrapfEigenBCGSolver_eigen.f
!! \brief Shroud generated wrapper for eigen namespace
!<
! splicer begin namespace.eigen.file_top
! splicer end namespace.eigen.file_top
module eigenbcgsolver_eigen_mod
    ! splicer begin namespace.eigen.module_use
    ! splicer end namespace.eigen.module_use
    implicit none

    ! splicer begin namespace.eigen.module_top
    ! splicer end namespace.eigen.module_top

    interface

        subroutine c_init_eigen_decomp_d(rows, cols, layers, dx, dy, dz, &
                thomas) &
                bind(C, name="EIG_eigen_initEigenDecomp_d")
            use iso_c_binding, only : C_BOOL, C_DOUBLE, C_SIZE_T
            implicit none
            integer(C_SIZE_T), value, intent(IN) :: rows
            integer(C_SIZE_T), value, intent(IN) :: cols
            integer(C_SIZE_T), value, intent(IN) :: layers
            real(C_DOUBLE), value, intent(IN) :: dx
            real(C_DOUBLE), value, intent(IN) :: dy
            real(C_DOUBLE), value, intent(IN) :: dz
            logical(C_BOOL), value, intent(IN) :: thomas
        end subroutine c_init_eigen_decomp_d

        subroutine c_init_eigen_decomp_s(rows, cols, layers, dx, dy, dz, &
                thomas) &
                bind(C, name="EIG_eigen_initEigenDecomp_s")
            use iso_c_binding, only : C_BOOL, C_DOUBLE, C_SIZE_T
            implicit none
            integer(C_SIZE_T), value, intent(IN) :: rows
            integer(C_SIZE_T), value, intent(IN) :: cols
            integer(C_SIZE_T), value, intent(IN) :: layers
            real(C_DOUBLE), value, intent(IN) :: dx
            real(C_DOUBLE), value, intent(IN) :: dy
            real(C_DOUBLE), value, intent(IN) :: dz
            logical(C_BOOL), value, intent(IN) :: thomas
        end subroutine c_init_eigen_decomp_s

        subroutine solve_eigen_decomp_d(x, b) &
                bind(C, name="EIG_eigen_solveEigenDecomp_d")
            use iso_c_binding, only : C_DOUBLE
            implicit none
            real(C_DOUBLE), intent(OUT) :: x(*)
            real(C_DOUBLE), intent(IN) :: b(*)
        end subroutine solve_eigen_decomp_d

        subroutine solve_eigen_decomp_s(x, b) &
                bind(C, name="EIG_eigen_solveEigenDecomp_s")
            use iso_c_binding, only : C_FLOAT
            implicit none
            real(C_FLOAT), intent(OUT) :: x(*)
            real(C_FLOAT), intent(IN) :: b(*)
        end subroutine solve_eigen_decomp_s

        subroutine finalize_eigen_decomp_d() &
                bind(C, name="EIG_eigen_finalizeEigenDecomp_d")
            implicit none
        end subroutine finalize_eigen_decomp_d

        subroutine finalize_eigen_decomp_s() &
                bind(C, name="EIG_eigen_finalizeEigenDecomp_s")
            implicit none
        end subroutine finalize_eigen_decomp_s
    end interface

    ! splicer begin namespace.eigen.additional_declarations
    ! splicer end namespace.eigen.additional_declarations

contains

    subroutine init_eigen_decomp_d(rows, cols, layers, dx, dy, dz, &
            thomas)
        use iso_c_binding, only : C_BOOL, C_DOUBLE, C_SIZE_T
        integer(C_SIZE_T), value, intent(IN) :: rows
        integer(C_SIZE_T), value, intent(IN) :: cols
        integer(C_SIZE_T), value, intent(IN) :: layers
        real(C_DOUBLE), value, intent(IN) :: dx
        real(C_DOUBLE), value, intent(IN) :: dy
        real(C_DOUBLE), value, intent(IN) :: dz
        logical, value, intent(IN) :: thomas
        ! splicer begin namespace.eigen.function.init_eigen_decomp_d
        logical(C_BOOL) :: SHT_thomas_cxx
        SHT_thomas_cxx = thomas  ! coerce to C_BOOL
        call c_init_eigen_decomp_d(rows, cols, layers, dx, dy, dz, &
            SHT_thomas_cxx)
        ! splicer end namespace.eigen.function.init_eigen_decomp_d
    end subroutine init_eigen_decomp_d

    subroutine init_eigen_decomp_s(rows, cols, layers, dx, dy, dz, &
            thomas)
        use iso_c_binding, only : C_BOOL, C_DOUBLE, C_SIZE_T
        integer(C_SIZE_T), value, intent(IN) :: rows
        integer(C_SIZE_T), value, intent(IN) :: cols
        integer(C_SIZE_T), value, intent(IN) :: layers
        real(C_DOUBLE), value, intent(IN) :: dx
        real(C_DOUBLE), value, intent(IN) :: dy
        real(C_DOUBLE), value, intent(IN) :: dz
        logical, value, intent(IN) :: thomas
        ! splicer begin namespace.eigen.function.init_eigen_decomp_s
        logical(C_BOOL) :: SHT_thomas_cxx
        SHT_thomas_cxx = thomas  ! coerce to C_BOOL
        call c_init_eigen_decomp_s(rows, cols, layers, dx, dy, dz, &
            SHT_thomas_cxx)
        ! splicer end namespace.eigen.function.init_eigen_decomp_s
    end subroutine init_eigen_decomp_s

    ! splicer begin namespace.eigen.additional_functions
    ! splicer end namespace.eigen.additional_functions

end module eigenbcgsolver_eigen_mod
