// wrapEigenBCGSolver_eigen.h
// This file is generated by Shroud 0.14.0. Do not edit.
/**
 * \file wrapEigenBCGSolver_eigen.h
 * \brief Shroud generated wrapper for eigen namespace
 */
// For C users and C++ implementation

#ifndef WRAPEIGENBCGSOLVER_EIGEN_H
#define WRAPEIGENBCGSOLVER_EIGEN_H

#ifdef __cplusplus
#include <cstddef>
#else
#include <stddef.h>
#include <stdbool.h>
#endif
#include "typesEigenBCGSolver.h"

// splicer begin namespace.eigen.CXX_declarations
// splicer end namespace.eigen.CXX_declarations

#ifdef __cplusplus
extern "C" {
#endif

// splicer begin namespace.eigen.C_declarations
// splicer end namespace.eigen.C_declarations

void EIG_eigen_initEigenDecomp_d(size_t rows, size_t cols,
    size_t layers, double dx, double dy, double dz, bool thomas);

void EIG_eigen_initEigenDecomp_s(size_t rows, size_t cols,
    size_t layers, double dx, double dy, double dz, bool thomas);

void EIG_eigen_solveEigenDecomp_d(double *x, double *b);

void EIG_eigen_solveEigenDecomp_s(float *x, float *b);

void EIG_eigen_finalizeEigenDecomp_d(void);

void EIG_eigen_finalizeEigenDecomp_s(void);

#ifdef __cplusplus
}
#endif

#endif  // WRAPEIGENBCGSOLVER_EIGEN_H
