// wrapEigenBCGSolver_ImEq.h
// This file is generated by Shroud 0.14.0. Do not edit.
/**
 * \file wrapEigenBCGSolver_ImEq.h
 * \brief Shroud generated wrapper for ImEq namespace
 */
// For C users and C++ implementation

#ifndef WRAPEIGENBCGSOLVER_IMEQ_H
#define WRAPEIGENBCGSOLVER_IMEQ_H

#ifdef __cplusplus
#include <cstddef>
#include <cstdint>
#else
#include <stddef.h>
#include <stdint.h>
#endif
#include "typesEigenBCGSolver.h"

// splicer begin namespace.ImEq.CXX_declarations
// splicer end namespace.ImEq.CXX_declarations

#ifdef __cplusplus
extern "C" {
#endif

// splicer begin namespace.ImEq.C_declarations
// splicer end namespace.ImEq.C_declarations

void EIG_ImEq_initImmersedEq_d_i32(size_t gridHeight, size_t gridWidth,
    size_t gridDepth, size_t fSize, size_t nnzMaxB, double *p,
    double *f, double deltaX, double deltaY, double deltaZ, double dt,
    double tolerance, size_t maxBCGIterations);

void EIG_ImEq_initImmersedEq_s_i32(size_t gridHeight, size_t gridWidth,
    size_t gridDepth, size_t fSize, size_t nnzMaxB, float *p, float *f,
    double deltaX, double deltaY, double deltaZ, double dt,
    double tolerance, size_t maxBCGIterations);

void EIG_ImEq_initImmersedEq_d_i64(size_t gridHeight, size_t gridWidth,
    size_t gridDepth, size_t fSize, size_t nnzMaxB, double *p,
    double *f, double deltaX, double deltaY, double deltaZ, double dt,
    double tolerance, size_t maxBCGIterations);

void EIG_ImEq_initImmersedEq_s_i64(size_t gridHeight, size_t gridWidth,
    size_t gridDepth, size_t fSize, size_t nnzMaxB, float *p, float *f,
    double deltaX, double deltaY, double deltaZ, double dt,
    double tolerance, size_t maxBCGIterations);

void EIG_ImEq_solveImmersedEq_d_i32(double *result, size_t nnzB,
    int32_t *rowOffsetsB, int32_t *colIndsB, double *valuesB);

void EIG_ImEq_solveImmersedEq_s_i32(float *result, size_t nnzB,
    int32_t *rowOffsetsB, int32_t *colIndsB, float *valuesB);

void EIG_ImEq_solveImmersedEq_d_i64(double *result, size_t nnzB,
    int64_t *rowOffsetsB, int64_t *colIndsB, double *valuesB);

void EIG_ImEq_solveImmersedEq_s_i64(float *result, size_t nnzB,
    int64_t *rowOffsetsB, int64_t *colIndsB, float *valuesB);

void EIG_ImEq_solveImmersedEqPrimes_d_i32(double *resultPPrime,
    double *resultFPrime, size_t nnzB, int32_t *rowOffsetsB,
    int32_t *colIndsB, double *valuesB, size_t nnzR,
    int32_t *colOffsetsR, int32_t *rowIndsR, double *valuesR,
    double *UGamma, double *uStar);

void EIG_ImEq_solveImmersedEqPrimes_s_i32(float *resultPPrime,
    float *resultFPrime, size_t nnzB, int32_t *rowOffsetsB,
    int32_t *colIndsB, float *valuesB, size_t nnzR,
    int32_t *colOffsetsR, int32_t *rowIndsR, float *valuesR,
    float *UGamma, float *uStar);

void EIG_ImEq_solveImmersedEqPrimes_d_i64(double *resultPPrime,
    double *resultFPrime, size_t nnzB, int64_t *rowOffsetsB,
    int64_t *colIndsB, double *valuesB, size_t nnzR,
    int64_t *colOffsetsR, int64_t *rowIndsR, double *valuesR,
    double *UGamma, double *uStar);

void EIG_ImEq_solveImmersedEqPrimes_s_i64(float *resultPPrime,
    float *resultFPrime, size_t nnzB, int64_t *rowOffsetsB,
    int64_t *colIndsB, float *valuesB, size_t nnzR,
    int64_t *colOffsetsR, int64_t *rowIndsR, float *valuesR,
    float *UGamma, float *uStar);

void EIG_ImEq_finalizeImmersedEq_d_i32(void);

void EIG_ImEq_finalizeImmersedEq_s_i32(void);

void EIG_ImEq_finalizeImmersedEq_d_i64(void);

void EIG_ImEq_finalizeImmersedEq_s_i64(void);

#ifdef __cplusplus
}
#endif

#endif  // WRAPEIGENBCGSOLVER_IMEQ_H
