// wrapFortranBindings.h
// This file is generated by Shroud 0.14.0. Do not edit.
/**
 * \file wrapFortranBindings.h
 * \brief Shroud generated wrapper for FortranBindings library
 */
// For C users and C++ implementation

#ifndef WRAPFORTRANBINDINGS_H
#define WRAPFORTRANBINDINGS_H

#ifdef __cplusplus
#include <cstddef>
#include <cstdint>
#else
#include <stddef.h>
#include <stdint.h>
#include <stdbool.h>
#endif
#include "typesFortranBindings.h"

// splicer begin CXX_declarations
// splicer end CXX_declarations

#ifdef __cplusplus
extern "C" {
#endif

// splicer begin C_declarations
// splicer end C_declarations

void FOR_initImmersedEq_d_i32(size_t gridHeight, size_t gridWidth,
    size_t gridDepth, size_t fSize, size_t nnzMaxB, double *p,
    double *f, double deltaX, double deltaY, double deltaZ,
    double tolerance, size_t maxBCGIterations);

void FOR_initImmersedEq_s_i32(size_t gridHeight, size_t gridWidth,
    size_t gridDepth, size_t fSize, size_t nnzMaxB, float *p, float *f,
    double deltaX, double deltaY, double deltaZ, double tolerance,
    size_t maxBCGIterations);

void FOR_initImmersedEq_d_i64(size_t gridHeight, size_t gridWidth,
    size_t gridDepth, size_t fSize, size_t nnzMaxB, double *p,
    double *f, double deltaX, double deltaY, double deltaZ,
    double tolerance, size_t maxBCGIterations);

void FOR_initImmersedEq_s_i64(size_t gridHeight, size_t gridWidth,
    size_t gridDepth, size_t fSize, size_t nnzMaxB, float *p, float *f,
    double deltaX, double deltaY, double deltaZ, double tolerance,
    size_t maxBCGIterations);

void FOR_solveImmersedEq_d_i32(double *result, size_t nnzB,
    int32_t *rowPointersB, int32_t *colOffsetsB, double *valuesB,
    bool multiStream);

void FOR_solveImmersedEq_s_i32(float *result, size_t nnzB,
    int32_t *rowPointersB, int32_t *colOffsetsB, float *valuesB,
    bool multiStream);

void FOR_solveImmersedEq_d_i64(double *result, size_t nnzB,
    int64_t *rowPointersB, int64_t *colOffsetsB, double *valuesB,
    bool multiStream);

void FOR_solveImmersedEq_s_i64(float *result, size_t nnzB,
    int64_t *rowPointersB, int64_t *colOffsetsB, float *valuesB,
    bool multiStream);

#ifdef __cplusplus
}
#endif

#endif  // WRAPFORTRANBINDINGS_H
