// wrapEigenBCGSolver_ImEq.cpp
// This file is generated by Shroud 0.14.0. Do not edit.

#include "FortranBindings.hpp"
#include "wrapEigenBCGSolver_ImEq.h"

// splicer begin namespace.ImEq.CXX_definitions
// splicer end namespace.ImEq.CXX_definitions

extern "C" {

// splicer begin namespace.ImEq.C_definitions
// splicer end namespace.ImEq.C_definitions

void EIG_ImEq_initImmersedEq_d_i32(size_t gridHeight, size_t gridWidth,
    size_t gridDepth, size_t fSize, size_t nnzMaxB, double *p,
    double *f, double deltaX, double deltaY, double deltaZ, double dt,
    double tolerance, size_t maxBCGIterations)
{
    // splicer begin namespace.ImEq.function.initImmersedEq_d_i32
    ImEq::initImmersedEq_d_i32(gridHeight, gridWidth, gridDepth, fSize,
        nnzMaxB, p, f, deltaX, deltaY, deltaZ, dt, tolerance,
        maxBCGIterations);
    // splicer end namespace.ImEq.function.initImmersedEq_d_i32
}

void EIG_ImEq_initImmersedEq_s_i32(size_t gridHeight, size_t gridWidth,
    size_t gridDepth, size_t fSize, size_t nnzMaxB, float *p, float *f,
    double deltaX, double deltaY, double deltaZ, double dt,
    double tolerance, size_t maxBCGIterations)
{
    // splicer begin namespace.ImEq.function.initImmersedEq_s_i32
    ImEq::initImmersedEq_s_i32(gridHeight, gridWidth, gridDepth, fSize,
        nnzMaxB, p, f, deltaX, deltaY, deltaZ, dt, tolerance,
        maxBCGIterations);
    // splicer end namespace.ImEq.function.initImmersedEq_s_i32
}

void EIG_ImEq_initImmersedEq_d_i64(size_t gridHeight, size_t gridWidth,
    size_t gridDepth, size_t fSize, size_t nnzMaxB, double *p,
    double *f, double deltaX, double deltaY, double deltaZ, double dt,
    double tolerance, size_t maxBCGIterations)
{
    // splicer begin namespace.ImEq.function.initImmersedEq_d_i64
    ImEq::initImmersedEq_d_i64(gridHeight, gridWidth, gridDepth, fSize,
        nnzMaxB, p, f, deltaX, deltaY, deltaZ, dt, tolerance,
        maxBCGIterations);
    // splicer end namespace.ImEq.function.initImmersedEq_d_i64
}

void EIG_ImEq_initImmersedEq_s_i64(size_t gridHeight, size_t gridWidth,
    size_t gridDepth, size_t fSize, size_t nnzMaxB, float *p, float *f,
    double deltaX, double deltaY, double deltaZ, double dt,
    double tolerance, size_t maxBCGIterations)
{
    // splicer begin namespace.ImEq.function.initImmersedEq_s_i64
    ImEq::initImmersedEq_s_i64(gridHeight, gridWidth, gridDepth, fSize,
        nnzMaxB, p, f, deltaX, deltaY, deltaZ, dt, tolerance,
        maxBCGIterations);
    // splicer end namespace.ImEq.function.initImmersedEq_s_i64
}

void EIG_ImEq_solveImmersedEq_d_i32(double *result, size_t nnzB,
    int32_t *rowOffsetsB, int32_t *colIndsB, double *valuesB)
{
    // splicer begin namespace.ImEq.function.solveImmersedEq_d_i32
    ImEq::solveImmersedEq_d_i32(result, nnzB, rowOffsetsB, colIndsB,
        valuesB);
    // splicer end namespace.ImEq.function.solveImmersedEq_d_i32
}

void EIG_ImEq_solveImmersedEq_s_i32(float *result, size_t nnzB,
    int32_t *rowOffsetsB, int32_t *colIndsB, float *valuesB)
{
    // splicer begin namespace.ImEq.function.solveImmersedEq_s_i32
    ImEq::solveImmersedEq_s_i32(result, nnzB, rowOffsetsB, colIndsB,
        valuesB);
    // splicer end namespace.ImEq.function.solveImmersedEq_s_i32
}

void EIG_ImEq_solveImmersedEq_d_i64(double *result, size_t nnzB,
    int64_t *rowOffsetsB, int64_t *colIndsB, double *valuesB)
{
    // splicer begin namespace.ImEq.function.solveImmersedEq_d_i64
    ImEq::solveImmersedEq_d_i64(result, nnzB, rowOffsetsB, colIndsB,
        valuesB);
    // splicer end namespace.ImEq.function.solveImmersedEq_d_i64
}

void EIG_ImEq_solveImmersedEq_s_i64(float *result, size_t nnzB,
    int64_t *rowOffsetsB, int64_t *colIndsB, float *valuesB)
{
    // splicer begin namespace.ImEq.function.solveImmersedEq_s_i64
    ImEq::solveImmersedEq_s_i64(result, nnzB, rowOffsetsB, colIndsB,
        valuesB);
    // splicer end namespace.ImEq.function.solveImmersedEq_s_i64
}

void EIG_ImEq_solveImmersedEqPrimes_d_i32(double *resultPPrime,
    double *resultFPrime, size_t nnzB, int32_t *rowOffsetsB,
    int32_t *colIndsB, double *valuesB, size_t nnzR,
    int32_t *colOffsetsR, int32_t *rowIndsR, double *valuesR,
    double *UGamma, double *uStar)
{
    // splicer begin namespace.ImEq.function.solveImmersedEqPrimes_d_i32
    ImEq::solveImmersedEqPrimes_d_i32(resultPPrime, resultFPrime, nnzB,
        rowOffsetsB, colIndsB, valuesB, nnzR, colOffsetsR, rowIndsR,
        valuesR, UGamma, uStar);
    // splicer end namespace.ImEq.function.solveImmersedEqPrimes_d_i32
}

void EIG_ImEq_solveImmersedEqPrimes_s_i32(float *resultPPrime,
    float *resultFPrime, size_t nnzB, int32_t *rowOffsetsB,
    int32_t *colIndsB, float *valuesB, size_t nnzR,
    int32_t *colOffsetsR, int32_t *rowIndsR, float *valuesR,
    float *UGamma, float *uStar)
{
    // splicer begin namespace.ImEq.function.solveImmersedEqPrimes_s_i32
    ImEq::solveImmersedEqPrimes_s_i32(resultPPrime, resultFPrime, nnzB,
        rowOffsetsB, colIndsB, valuesB, nnzR, colOffsetsR, rowIndsR,
        valuesR, UGamma, uStar);
    // splicer end namespace.ImEq.function.solveImmersedEqPrimes_s_i32
}

void EIG_ImEq_solveImmersedEqPrimes_d_i64(double *resultPPrime,
    double *resultFPrime, size_t nnzB, int64_t *rowOffsetsB,
    int64_t *colIndsB, double *valuesB, size_t nnzR,
    int64_t *colOffsetsR, int64_t *rowIndsR, double *valuesR,
    double *UGamma, double *uStar)
{
    // splicer begin namespace.ImEq.function.solveImmersedEqPrimes_d_i64
    ImEq::solveImmersedEqPrimes_d_i64(resultPPrime, resultFPrime, nnzB,
        rowOffsetsB, colIndsB, valuesB, nnzR, colOffsetsR, rowIndsR,
        valuesR, UGamma, uStar);
    // splicer end namespace.ImEq.function.solveImmersedEqPrimes_d_i64
}

void EIG_ImEq_solveImmersedEqPrimes_s_i64(float *resultPPrime,
    float *resultFPrime, size_t nnzB, int64_t *rowOffsetsB,
    int64_t *colIndsB, float *valuesB, size_t nnzR,
    int64_t *colOffsetsR, int64_t *rowIndsR, float *valuesR,
    float *UGamma, float *uStar)
{
    // splicer begin namespace.ImEq.function.solveImmersedEqPrimes_s_i64
    ImEq::solveImmersedEqPrimes_s_i64(resultPPrime, resultFPrime, nnzB,
        rowOffsetsB, colIndsB, valuesB, nnzR, colOffsetsR, rowIndsR,
        valuesR, UGamma, uStar);
    // splicer end namespace.ImEq.function.solveImmersedEqPrimes_s_i64
}

void EIG_ImEq_finalizeImmersedEq_d_i32(void)
{
    // splicer begin namespace.ImEq.function.finalizeImmersedEq_d_i32
    ImEq::finalizeImmersedEq_d_i32();
    // splicer end namespace.ImEq.function.finalizeImmersedEq_d_i32
}

void EIG_ImEq_finalizeImmersedEq_s_i32(void)
{
    // splicer begin namespace.ImEq.function.finalizeImmersedEq_s_i32
    ImEq::finalizeImmersedEq_s_i32();
    // splicer end namespace.ImEq.function.finalizeImmersedEq_s_i32
}

void EIG_ImEq_finalizeImmersedEq_d_i64(void)
{
    // splicer begin namespace.ImEq.function.finalizeImmersedEq_d_i64
    ImEq::finalizeImmersedEq_d_i64();
    // splicer end namespace.ImEq.function.finalizeImmersedEq_d_i64
}

void EIG_ImEq_finalizeImmersedEq_s_i64(void)
{
    // splicer begin namespace.ImEq.function.finalizeImmersedEq_s_i64
    ImEq::finalizeImmersedEq_s_i64();
    // splicer end namespace.ImEq.function.finalizeImmersedEq_s_i64
}

}  // extern "C"
