// wrapEigenBCGSolver_ImEq.h
// This file is generated by Shroud 0.14.0. Do not edit.
/**
 * \file wrapEigenBCGSolver_ImEq.h
 * \brief Shroud generated wrapper for ImEq namespace
 */
// For C users and C++ implementation

#ifndef WRAPEIGENBCGSOLVER_IMEQ_H
#define WRAPEIGENBCGSOLVER_IMEQ_H

#ifdef __cplusplus
#include <cstddef>
#include <cstdint>
#else
#include <stddef.h>
#include <stdbool.h>
#include <stdint.h>
#endif
#include "typesEigenBCGSolver.h"

// splicer begin namespace.ImEq.CXX_declarations
// splicer end namespace.ImEq.CXX_declarations

#ifdef __cplusplus
extern "C" {
#endif

// splicer begin namespace.ImEq.C_declarations
// splicer end namespace.ImEq.C_declarations

void EIG_ImEq_initImmersedEq_d_i32(size_t dim1Length, size_t dim2Length,
    size_t dim3Length, bool dim1StartIsNeumann, bool dim1EndIsNeumann,
    bool dim2StartIsNeumann, bool dim2EndIsNeumann,
    bool dim3StartIsNeumann, bool dim3EndIsNeumann, double dim1StartVal,
    double dim1EndVal, double dim2StartVal, double dim2EndVal,
    double dim3StartVal, double dim3EndVal, size_t dim1SegSpacing,
    size_t dim2SegSpacing, size_t dim3SegSpacing, size_t forceSize,
    size_t nnzMax, double *p, double *f, double *dim1Delta,
    double *dim2Delta, double *dim3Delta, double dt,
    bool dim1UniformDelta, bool dim2UniformDelta, bool dim3UniformDelta,
    double tol, size_t maxIterations);

void EIG_ImEq_initImmersedEq_s_i32(size_t dim1Length, size_t dim2Length,
    size_t dim3Length, bool dim1StartIsNeumann, bool dim1EndIsNeumann,
    bool dim2StartIsNeumann, bool dim2EndIsNeumann,
    bool dim3StartIsNeumann, bool dim3EndIsNeumann, double dim1StartVal,
    double dim1EndVal, double dim2StartVal, double dim2EndVal,
    double dim3StartVal, double dim3EndVal, size_t dim1SegSpacing,
    size_t dim2SegSpacing, size_t dim3SegSpacing, size_t forceSize,
    size_t nnzMax, float *p, float *f, float *dim1Delta,
    float *dim2Delta, float *dim3Delta, double dt,
    bool dim1UniformDelta, bool dim2UniformDelta, bool dim3UniformDelta,
    double tol, size_t maxIterations);

void EIG_ImEq_initImmersedEq_d_i64(size_t dim1Length, size_t dim2Length,
    size_t dim3Length, bool dim1StartIsNeumann, bool dim1EndIsNeumann,
    bool dim2StartIsNeumann, bool dim2EndIsNeumann,
    bool dim3StartIsNeumann, bool dim3EndIsNeumann, double dim1StartVal,
    double dim1EndVal, double dim2StartVal, double dim2EndVal,
    double dim3StartVal, double dim3EndVal, size_t dim1SegSpacing,
    size_t dim2SegSpacing, size_t dim3SegSpacing, size_t forceSize,
    size_t nnzMax, double *p, double *f, double *dim1Delta,
    double *dim2Delta, double *dim3Delta, double dt,
    bool dim1UniformDelta, bool dim2UniformDelta, bool dim3UniformDelta,
    double tol, size_t maxIterations);

void EIG_ImEq_initImmersedEq_s_i64(size_t dim1Length, size_t dim2Length,
    size_t dim3Length, bool dim1StartIsNeumann, bool dim1EndIsNeumann,
    bool dim2StartIsNeumann, bool dim2EndIsNeumann,
    bool dim3StartIsNeumann, bool dim3EndIsNeumann, float dim1StartVal,
    float dim1EndVal, float dim2StartVal, float dim2EndVal,
    float dim3StartVal, float dim3EndVal, size_t dim1SegSpacing,
    size_t dim2SegSpacing, size_t dim3SegSpacing, size_t forceSize,
    size_t nnzMax, float *p, float *f, float *dim1Delta,
    float *dim2Delta, float *dim3Delta, double dt,
    bool dim1UniformDelta, bool dim2UniformDelta, bool dim3UniformDelta,
    double tol, size_t maxIterations);

void EIG_ImEq_solveImmersedEq_d_i32_0(double *result, size_t nnzB,
    int32_t *rowOffsetsB, int32_t *colIndsB, double *val);

void EIG_ImEq_solveImmersedEq_d_i32_1(double *result, size_t nnzB,
    int32_t *rowOffsetsB, int32_t *colIndsB, double *val, bool multi);

void EIG_ImEq_solveImmersedEq_s_i32_0(float *result, size_t nnzB,
    int32_t *rowOffsetsB, int32_t *colIndsB, float *val);

void EIG_ImEq_solveImmersedEq_s_i32_1(float *result, size_t nnzB,
    int32_t *rowOffsetsB, int32_t *colIndsB, float *val, bool multi);

void EIG_ImEq_solveImmersedEq_d_i64_0(double *result, size_t nnzB,
    int64_t *rowOffsetsB, int64_t *colIndsB, double *val);

void EIG_ImEq_solveImmersedEq_d_i64_1(double *result, size_t nnzB,
    int64_t *rowOffsetsB, int64_t *colIndsB, double *val, bool multi);

void EIG_ImEq_solveImmersedEq_s_i64_0(float *result, size_t nnzB,
    int64_t *rowOffsetsB, int64_t *colIndsB, float *val);

void EIG_ImEq_solveImmersedEq_s_i64_1(float *result, size_t nnzB,
    int64_t *rowOffsetsB, int64_t *colIndsB, float *val, bool multi);

void EIG_ImEq_solveImmersedEqPrimes_d_i32(double *resultPPrime,
    double *resultFPrime, size_t nnzB, int32_t *rowOffsetsB,
    int32_t *colIndsB, double *valuesB, size_t nnzR,
    int32_t *colOffsetsR, int32_t *rowIndsR, double *valuesR,
    double *UGamma, double *uStar);

void EIG_ImEq_solveImmersedEqPrimes_s_i32(float *resultPPrime,
    float *resultFPrime, size_t nnzB, int32_t *rowOffsetsB,
    int32_t *colIndsB, float *valuesB, size_t nnzR,
    int32_t *colOffsetsR, int32_t *rowIndsR, float *valuesR,
    float *UGamma, float *uStar);

void EIG_ImEq_solveImmersedEqPrimes_d_i64(double *resultPPrime,
    double *resultFPrime, size_t nnzB, int64_t *rowOffsetsB,
    int64_t *colIndsB, double *valuesB, size_t nnzR,
    int64_t *colOffsetsR, int64_t *rowIndsR, double *valuesR,
    double *UGamma, double *uStar);

void EIG_ImEq_solveImmersedEqPrimes_s_i64(float *resultPPrime,
    float *resultFPrime, size_t nnzB, int64_t *rowOffsetsB,
    int64_t *colIndsB, float *valuesB, size_t nnzR,
    int64_t *colOffsetsR, int64_t *rowIndsR, float *valuesR,
    float *UGamma, float *uStar);

void EIG_ImEq_finalizeImmersedEq_d_i32(void);

void EIG_ImEq_finalizeImmersedEq_s_i32(void);

void EIG_ImEq_finalizeImmersedEq_d_i64(void);

void EIG_ImEq_finalizeImmersedEq_s_i64(void);

#ifdef __cplusplus
}
#endif

#endif  // WRAPEIGENBCGSOLVER_IMEQ_H
