! wrapfeigenbcgsolver.f
! This file is generated by Shroud 0.14.0. Do not edit.
!>
!! \file wrapfeigenbcgsolver.f
!! \brief Shroud generated wrapper for EigenBCGSolver library
!<
! splicer begin file_top
! splicer end file_top
module eigenbcgsolver_mod
    ! splicer begin module_use
    ! splicer end module_use
    implicit none

    ! splicer begin module_top
    ! splicer end module_top

    ! splicer begin additional_declarations
    ! splicer end additional_declarations

contains

    ! splicer begin additional_functions
    ! splicer end additional_functions

end module eigenbcgsolver_mod
