// wrapEigenBCGSolver_eigen.cpp
// This file is generated by Shroud 0.14.0. Do not edit.

#include "FortranBindings.hpp"
#include "wrapEigenBCGSolver_eigen.h"

// splicer begin namespace.eigen.CXX_definitions
// splicer end namespace.eigen.CXX_definitions

extern "C" {

// splicer begin namespace.eigen.C_definitions
// splicer end namespace.eigen.C_definitions

size_t EIG_eigen_initEigenDecomp_d(size_t rows, size_t cols,
    size_t layers, double *dx, double *dy, double *dz,
    bool uniformDeltaX, bool uniformDeltaY, bool uniformDeltaZ,
    bool leftIsNeumann, bool rightIsNeumann, bool topIsNeumann,
    bool bottomIsNeumann, bool backIsNeumann, bool frontIsNeumann,
    double leftVal, double rightVal, double topVal, double bottomVal,
    double frontVal, double backVal, bool isStaggered, bool thomas)
{
    // splicer begin namespace.eigen.function.initEigenDecomp_d
    size_t SHC_rv = eigen::initEigenDecomp_d(rows, cols, layers, dx, dy,
        dz, uniformDeltaX, uniformDeltaY, uniformDeltaZ, leftIsNeumann,
        rightIsNeumann, topIsNeumann, bottomIsNeumann, backIsNeumann,
        frontIsNeumann, leftVal, rightVal, topVal, bottomVal, frontVal,
        backVal, isStaggered, thomas);
    return SHC_rv;
    // splicer end namespace.eigen.function.initEigenDecomp_d
}

size_t EIG_eigen_initEigenDecomp_s(size_t rows, size_t cols,
    size_t layers, float *dx, float *dy, float *dz, bool uniformDeltaX,
    bool uniformDeltaY, bool uniformDeltaZ, bool leftIsNeumann,
    bool rightIsNeumann, bool topIsNeumann, bool bottomIsNeumann,
    bool backIsNeumann, bool frontIsNeumann, float leftVal,
    float rightVal, float topVal, float bottomVal, float frontVal,
    float backVal, bool isStaggered, bool thomas)
{
    // splicer begin namespace.eigen.function.initEigenDecomp_s
    size_t SHC_rv = eigen::initEigenDecomp_s(rows, cols, layers, dx, dy,
        dz, uniformDeltaX, uniformDeltaY, uniformDeltaZ, leftIsNeumann,
        rightIsNeumann, topIsNeumann, bottomIsNeumann, backIsNeumann,
        frontIsNeumann, leftVal, rightVal, topVal, bottomVal, frontVal,
        backVal, isStaggered, thomas);
    return SHC_rv;
    // splicer end namespace.eigen.function.initEigenDecomp_s
}

void EIG_eigen_solveEigenDecomp_d(size_t solverHandle, double *x,
    double *b)
{
    // splicer begin namespace.eigen.function.solveEigenDecomp_d
    eigen::solveEigenDecomp_d(solverHandle, x, b);
    // splicer end namespace.eigen.function.solveEigenDecomp_d
}

void EIG_eigen_solveEigenDecomp_s(size_t solverHandle, float *x,
    float *b)
{
    // splicer begin namespace.eigen.function.solveEigenDecomp_s
    eigen::solveEigenDecomp_s(solverHandle, x, b);
    // splicer end namespace.eigen.function.solveEigenDecomp_s
}

void EIG_eigen_finalizeEigenDecomp_d(void)
{
    // splicer begin namespace.eigen.function.finalizeEigenDecomp_d
    eigen::finalizeEigenDecomp_d();
    // splicer end namespace.eigen.function.finalizeEigenDecomp_d
}

void EIG_eigen_finalizeEigenDecomp_s(void)
{
    // splicer begin namespace.eigen.function.finalizeEigenDecomp_s
    eigen::finalizeEigenDecomp_s();
    // splicer end namespace.eigen.function.finalizeEigenDecomp_s
}

}  // extern "C"
