! wrapfEigenBCGSolver_eigen.f
! This file is generated by Shroud 0.14.0. Do not edit.
!>
!! \file wrapfEigenBCGSolver_eigen.f
!! \brief Shroud generated wrapper for eigen namespace
!<
! splicer begin namespace.eigen.file_top
! splicer end namespace.eigen.file_top
module eigenbcgsolver_eigen_mod
    ! splicer begin namespace.eigen.module_use
    ! splicer end namespace.eigen.module_use
    implicit none

    ! splicer begin namespace.eigen.module_top
    ! splicer end namespace.eigen.module_top

    interface

        function c_init_eigen_decomp_d(dim1Length, dim2Length, &
                dim3Length, dim1Delta, dim2Delta, dim3Delta, &
                dim1SegType, dim2SegType, dim3SegType, &
                dim1StartIsNeumann, dim1EndIsNeumann, &
                dim2StartIsNeumann, dim2EndIsNeumann, &
                dim3StartIsNeumann, dim3EndIsNeumann, dim1StartVal, &
                dim1EndVal, dim2StartVal, dim2EndVal, dim3StartVal, &
                dim3EndVal, thomas, helmholtzShift, gpuInd) &
                result(SHT_rv) &
                bind(C, name="EIG_eigen_initEigenDecomp_d")
            use iso_c_binding, only : C_BOOL, C_DOUBLE, C_INT, C_SIZE_T
            implicit none
            integer(C_SIZE_T), value, intent(IN) :: dim1Length
            integer(C_SIZE_T), value, intent(IN) :: dim2Length
            integer(C_SIZE_T), value, intent(IN) :: dim3Length
            real(C_DOUBLE), intent(IN) :: dim1Delta(*)
            real(C_DOUBLE), intent(IN) :: dim2Delta(*)
            real(C_DOUBLE), intent(IN) :: dim3Delta(*)
            integer(C_INT), value, intent(IN) :: dim1SegType
            integer(C_INT), value, intent(IN) :: dim2SegType
            integer(C_INT), value, intent(IN) :: dim3SegType
            logical(C_BOOL), value, intent(IN) :: dim1StartIsNeumann
            logical(C_BOOL), value, intent(IN) :: dim1EndIsNeumann
            logical(C_BOOL), value, intent(IN) :: dim2StartIsNeumann
            logical(C_BOOL), value, intent(IN) :: dim2EndIsNeumann
            logical(C_BOOL), value, intent(IN) :: dim3StartIsNeumann
            logical(C_BOOL), value, intent(IN) :: dim3EndIsNeumann
            real(C_DOUBLE), value, intent(IN) :: dim1StartVal
            real(C_DOUBLE), value, intent(IN) :: dim1EndVal
            real(C_DOUBLE), value, intent(IN) :: dim2StartVal
            real(C_DOUBLE), value, intent(IN) :: dim2EndVal
            real(C_DOUBLE), value, intent(IN) :: dim3StartVal
            real(C_DOUBLE), value, intent(IN) :: dim3EndVal
            logical(C_BOOL), value, intent(IN) :: thomas
            real(C_DOUBLE), value, intent(IN) :: helmholtzShift
            integer(C_SIZE_T), value, intent(IN) :: gpuInd
            integer(C_SIZE_T) :: SHT_rv
        end function c_init_eigen_decomp_d

        function c_init_eigen_decomp_s(dim1Length, dim2Length, &
                dim3Length, dim1Delta, dim2Delta, dim3Delta, &
                dim1SegType, dim2SegType, dim3SegType, &
                dim1StartIsNeumann, dim1EndIsNeumann, &
                dim2StartIsNeumann, dim2EndIsNeumann, &
                dim3StartIsNeumann, dim3EndIsNeumann, dim1StartVal, &
                dim1EndVal, dim2StartVal, dim2EndVal, dim3StartVal, &
                dim3EndVal, thomas, helmholtzShift, gpuInd) &
                result(SHT_rv) &
                bind(C, name="EIG_eigen_initEigenDecomp_s")
            use iso_c_binding, only : C_BOOL, C_FLOAT, C_INT, C_SIZE_T
            implicit none
            integer(C_SIZE_T), value, intent(IN) :: dim1Length
            integer(C_SIZE_T), value, intent(IN) :: dim2Length
            integer(C_SIZE_T), value, intent(IN) :: dim3Length
            real(C_FLOAT), intent(IN) :: dim1Delta(*)
            real(C_FLOAT), intent(IN) :: dim2Delta(*)
            real(C_FLOAT), intent(IN) :: dim3Delta(*)
            integer(C_INT), value, intent(IN) :: dim1SegType
            integer(C_INT), value, intent(IN) :: dim2SegType
            integer(C_INT), value, intent(IN) :: dim3SegType
            logical(C_BOOL), value, intent(IN) :: dim1StartIsNeumann
            logical(C_BOOL), value, intent(IN) :: dim1EndIsNeumann
            logical(C_BOOL), value, intent(IN) :: dim2StartIsNeumann
            logical(C_BOOL), value, intent(IN) :: dim2EndIsNeumann
            logical(C_BOOL), value, intent(IN) :: dim3StartIsNeumann
            logical(C_BOOL), value, intent(IN) :: dim3EndIsNeumann
            real(C_FLOAT), value, intent(IN) :: dim1StartVal
            real(C_FLOAT), value, intent(IN) :: dim1EndVal
            real(C_FLOAT), value, intent(IN) :: dim2StartVal
            real(C_FLOAT), value, intent(IN) :: dim2EndVal
            real(C_FLOAT), value, intent(IN) :: dim3StartVal
            real(C_FLOAT), value, intent(IN) :: dim3EndVal
            logical(C_BOOL), value, intent(IN) :: thomas
            real(C_FLOAT), value, intent(IN) :: helmholtzShift
            integer(C_SIZE_T), value, intent(IN) :: gpuInd
            integer(C_SIZE_T) :: SHT_rv
        end function c_init_eigen_decomp_s

        subroutine solve_eigen_decomp_d(solverHandle, b) &
                bind(C, name="EIG_eigen_solveEigenDecomp_d")
            use iso_c_binding, only : C_DOUBLE, C_SIZE_T
            implicit none
            integer(C_SIZE_T), value, intent(IN) :: solverHandle
            real(C_DOUBLE), intent(IN) :: b(*)
        end subroutine solve_eigen_decomp_d

        subroutine solve_eigen_decomp_s(solverHandle, b) &
                bind(C, name="EIG_eigen_solveEigenDecomp_s")
            use iso_c_binding, only : C_FLOAT, C_SIZE_T
            implicit none
            integer(C_SIZE_T), value, intent(IN) :: solverHandle
            real(C_FLOAT), intent(IN) :: b(*)
        end subroutine solve_eigen_decomp_s

        subroutine synch_d(solverHandle, x) &
                bind(C, name="EIG_eigen_synch_d")
            use iso_c_binding, only : C_DOUBLE, C_SIZE_T
            implicit none
            integer(C_SIZE_T), value, intent(IN) :: solverHandle
            real(C_DOUBLE), intent(OUT) :: x(*)
        end subroutine synch_d

        subroutine synch_s(solverHandle, x) &
                bind(C, name="EIG_eigen_synch_s")
            use iso_c_binding, only : C_FLOAT, C_SIZE_T
            implicit none
            integer(C_SIZE_T), value, intent(IN) :: solverHandle
            real(C_FLOAT), intent(OUT) :: x(*)
        end subroutine synch_s

        subroutine finalize_eigen_decomp() &
                bind(C, name="EIG_eigen_finalizeEigenDecomp")
            implicit none
        end subroutine finalize_eigen_decomp
    end interface

    ! splicer begin namespace.eigen.additional_declarations
    ! splicer end namespace.eigen.additional_declarations

contains

    function init_eigen_decomp_d(dim1Length, dim2Length, dim3Length, &
            dim1Delta, dim2Delta, dim3Delta, dim1SegType, dim2SegType, &
            dim3SegType, dim1StartIsNeumann, dim1EndIsNeumann, &
            dim2StartIsNeumann, dim2EndIsNeumann, dim3StartIsNeumann, &
            dim3EndIsNeumann, dim1StartVal, dim1EndVal, dim2StartVal, &
            dim2EndVal, dim3StartVal, dim3EndVal, thomas, &
            helmholtzShift, gpuInd) &
            result(SHT_rv)
        use iso_c_binding, only : C_BOOL, C_DOUBLE, C_INT, C_SIZE_T
        integer(C_SIZE_T), value, intent(IN) :: dim1Length
        integer(C_SIZE_T), value, intent(IN) :: dim2Length
        integer(C_SIZE_T), value, intent(IN) :: dim3Length
        real(C_DOUBLE), intent(IN) :: dim1Delta(:)
        real(C_DOUBLE), intent(IN) :: dim2Delta(:)
        real(C_DOUBLE), intent(IN) :: dim3Delta(:)
        integer(C_INT), value, intent(IN) :: dim1SegType
        integer(C_INT), value, intent(IN) :: dim2SegType
        integer(C_INT), value, intent(IN) :: dim3SegType
        logical, value, intent(IN) :: dim1StartIsNeumann
        logical, value, intent(IN) :: dim1EndIsNeumann
        logical, value, intent(IN) :: dim2StartIsNeumann
        logical, value, intent(IN) :: dim2EndIsNeumann
        logical, value, intent(IN) :: dim3StartIsNeumann
        logical, value, intent(IN) :: dim3EndIsNeumann
        real(C_DOUBLE), value, intent(IN) :: dim1StartVal
        real(C_DOUBLE), value, intent(IN) :: dim1EndVal
        real(C_DOUBLE), value, intent(IN) :: dim2StartVal
        real(C_DOUBLE), value, intent(IN) :: dim2EndVal
        real(C_DOUBLE), value, intent(IN) :: dim3StartVal
        real(C_DOUBLE), value, intent(IN) :: dim3EndVal
        logical, value, intent(IN) :: thomas
        real(C_DOUBLE), value, intent(IN) :: helmholtzShift
        integer(C_SIZE_T), value, intent(IN) :: gpuInd
        integer(C_SIZE_T) :: SHT_rv
        ! splicer begin namespace.eigen.function.init_eigen_decomp_d
        logical(C_BOOL) :: SHT_dim1StartIsNeumann_cxx
        logical(C_BOOL) :: SHT_dim1EndIsNeumann_cxx
        logical(C_BOOL) :: SHT_dim2StartIsNeumann_cxx
        logical(C_BOOL) :: SHT_dim2EndIsNeumann_cxx
        logical(C_BOOL) :: SHT_dim3StartIsNeumann_cxx
        logical(C_BOOL) :: SHT_dim3EndIsNeumann_cxx
        logical(C_BOOL) :: SHT_thomas_cxx
        SHT_dim1StartIsNeumann_cxx = dim1StartIsNeumann  ! coerce to C_BOOL
        SHT_dim1EndIsNeumann_cxx = dim1EndIsNeumann  ! coerce to C_BOOL
        SHT_dim2StartIsNeumann_cxx = dim2StartIsNeumann  ! coerce to C_BOOL
        SHT_dim2EndIsNeumann_cxx = dim2EndIsNeumann  ! coerce to C_BOOL
        SHT_dim3StartIsNeumann_cxx = dim3StartIsNeumann  ! coerce to C_BOOL
        SHT_dim3EndIsNeumann_cxx = dim3EndIsNeumann  ! coerce to C_BOOL
        SHT_thomas_cxx = thomas  ! coerce to C_BOOL
        SHT_rv = c_init_eigen_decomp_d(dim1Length, dim2Length, &
            dim3Length, dim1Delta, dim2Delta, dim3Delta, dim1SegType, &
            dim2SegType, dim3SegType, SHT_dim1StartIsNeumann_cxx, &
            SHT_dim1EndIsNeumann_cxx, SHT_dim2StartIsNeumann_cxx, &
            SHT_dim2EndIsNeumann_cxx, SHT_dim3StartIsNeumann_cxx, &
            SHT_dim3EndIsNeumann_cxx, dim1StartVal, dim1EndVal, &
            dim2StartVal, dim2EndVal, dim3StartVal, dim3EndVal, &
            SHT_thomas_cxx, helmholtzShift, gpuInd)
        ! splicer end namespace.eigen.function.init_eigen_decomp_d
    end function init_eigen_decomp_d

    function init_eigen_decomp_s(dim1Length, dim2Length, dim3Length, &
            dim1Delta, dim2Delta, dim3Delta, dim1SegType, dim2SegType, &
            dim3SegType, dim1StartIsNeumann, dim1EndIsNeumann, &
            dim2StartIsNeumann, dim2EndIsNeumann, dim3StartIsNeumann, &
            dim3EndIsNeumann, dim1StartVal, dim1EndVal, dim2StartVal, &
            dim2EndVal, dim3StartVal, dim3EndVal, thomas, &
            helmholtzShift, gpuInd) &
            result(SHT_rv)
        use iso_c_binding, only : C_BOOL, C_FLOAT, C_INT, C_SIZE_T
        integer(C_SIZE_T), value, intent(IN) :: dim1Length
        integer(C_SIZE_T), value, intent(IN) :: dim2Length
        integer(C_SIZE_T), value, intent(IN) :: dim3Length
        real(C_FLOAT), intent(IN) :: dim1Delta(:)
        real(C_FLOAT), intent(IN) :: dim2Delta(:)
        real(C_FLOAT), intent(IN) :: dim3Delta(:)
        integer(C_INT), value, intent(IN) :: dim1SegType
        integer(C_INT), value, intent(IN) :: dim2SegType
        integer(C_INT), value, intent(IN) :: dim3SegType
        logical, value, intent(IN) :: dim1StartIsNeumann
        logical, value, intent(IN) :: dim1EndIsNeumann
        logical, value, intent(IN) :: dim2StartIsNeumann
        logical, value, intent(IN) :: dim2EndIsNeumann
        logical, value, intent(IN) :: dim3StartIsNeumann
        logical, value, intent(IN) :: dim3EndIsNeumann
        real(C_FLOAT), value, intent(IN) :: dim1StartVal
        real(C_FLOAT), value, intent(IN) :: dim1EndVal
        real(C_FLOAT), value, intent(IN) :: dim2StartVal
        real(C_FLOAT), value, intent(IN) :: dim2EndVal
        real(C_FLOAT), value, intent(IN) :: dim3StartVal
        real(C_FLOAT), value, intent(IN) :: dim3EndVal
        logical, value, intent(IN) :: thomas
        real(C_FLOAT), value, intent(IN) :: helmholtzShift
        integer(C_SIZE_T), value, intent(IN) :: gpuInd
        integer(C_SIZE_T) :: SHT_rv
        ! splicer begin namespace.eigen.function.init_eigen_decomp_s
        logical(C_BOOL) :: SHT_dim1StartIsNeumann_cxx
        logical(C_BOOL) :: SHT_dim1EndIsNeumann_cxx
        logical(C_BOOL) :: SHT_dim2StartIsNeumann_cxx
        logical(C_BOOL) :: SHT_dim2EndIsNeumann_cxx
        logical(C_BOOL) :: SHT_dim3StartIsNeumann_cxx
        logical(C_BOOL) :: SHT_dim3EndIsNeumann_cxx
        logical(C_BOOL) :: SHT_thomas_cxx
        SHT_dim1StartIsNeumann_cxx = dim1StartIsNeumann  ! coerce to C_BOOL
        SHT_dim1EndIsNeumann_cxx = dim1EndIsNeumann  ! coerce to C_BOOL
        SHT_dim2StartIsNeumann_cxx = dim2StartIsNeumann  ! coerce to C_BOOL
        SHT_dim2EndIsNeumann_cxx = dim2EndIsNeumann  ! coerce to C_BOOL
        SHT_dim3StartIsNeumann_cxx = dim3StartIsNeumann  ! coerce to C_BOOL
        SHT_dim3EndIsNeumann_cxx = dim3EndIsNeumann  ! coerce to C_BOOL
        SHT_thomas_cxx = thomas  ! coerce to C_BOOL
        SHT_rv = c_init_eigen_decomp_s(dim1Length, dim2Length, &
            dim3Length, dim1Delta, dim2Delta, dim3Delta, dim1SegType, &
            dim2SegType, dim3SegType, SHT_dim1StartIsNeumann_cxx, &
            SHT_dim1EndIsNeumann_cxx, SHT_dim2StartIsNeumann_cxx, &
            SHT_dim2EndIsNeumann_cxx, SHT_dim3StartIsNeumann_cxx, &
            SHT_dim3EndIsNeumann_cxx, dim1StartVal, dim1EndVal, &
            dim2StartVal, dim2EndVal, dim3StartVal, dim3EndVal, &
            SHT_thomas_cxx, helmholtzShift, gpuInd)
        ! splicer end namespace.eigen.function.init_eigen_decomp_s
    end function init_eigen_decomp_s

    ! splicer begin namespace.eigen.additional_functions
    ! splicer end namespace.eigen.additional_functions

end module eigenbcgsolver_eigen_mod
