// wrapEigenBCGSolver_eigen.h
// This file is generated by Shroud 0.14.0. Do not edit.
/**
 * \file wrapEigenBCGSolver_eigen.h
 * \brief Shroud generated wrapper for eigen namespace
 */
// For C users and C++ implementation

#ifndef WRAPEIGENBCGSOLVER_EIGEN_H
#define WRAPEIGENBCGSOLVER_EIGEN_H

#ifdef __cplusplus
#include <cstddef>
#else
#include <stddef.h>
#include <stdbool.h>
#endif
#include "typesEigenBCGSolver.h"

// splicer begin namespace.eigen.CXX_declarations
// splicer end namespace.eigen.CXX_declarations

#ifdef __cplusplus
extern "C" {
#endif

// splicer begin namespace.eigen.C_declarations
// splicer end namespace.eigen.C_declarations

size_t EIG_eigen_initEigenDecomp_d(size_t rows, size_t cols,
    size_t layers, double *dx, double *dy, double *dz,
    bool uniformDeltaX, bool uniformDeltaY, bool uniformDeltaZ,
    bool leftIsNeumann, bool rightIsNeumann, bool topIsNeumann,
    bool bottomIsNeumann, bool frontIsNeumann, bool backIsNeumann,
    double leftVal, double rightVal, double topVal, double bottomVal,
    double frontVal, double backVal, bool isStaggered, bool thomas);

size_t EIG_eigen_initEigenDecomp_s(size_t rows, size_t cols,
    size_t layers, float *dx, float *dy, float *dz, bool uniformDeltaX,
    bool uniformDeltaY, bool uniformDeltaZ, bool leftIsNeumann,
    bool rightIsNeumann, bool topIsNeumann, bool bottomIsNeumann,
    bool frontIsNeumann, bool backIsNeumann, float leftVal,
    float rightVal, float topVal, float bottomVal, float frontVal,
    float backVal, bool isStaggered, bool thomas);

void EIG_eigen_solveEigenDecomp_d(size_t solverHandle, double *x,
    double *b);

void EIG_eigen_solveEigenDecomp_s(size_t solverHandle, float *x,
    float *b);

void EIG_eigen_finalizeEigenDecomp_d(void);

void EIG_eigen_finalizeEigenDecomp_s(void);

#ifdef __cplusplus
}
#endif

#endif  // WRAPEIGENBCGSOLVER_EIGEN_H
