! wrapfEigenBCGSolver_eigen.f
! This file is generated by Shroud 0.14.0. Do not edit.
!>
!! \file wrapfEigenBCGSolver_eigen.f
!! \brief Shroud generated wrapper for eigen namespace
!<
! splicer begin namespace.eigen.file_top
! splicer end namespace.eigen.file_top
module eigenbcgsolver_eigen_mod
    ! splicer begin namespace.eigen.module_use
    ! splicer end namespace.eigen.module_use
    implicit none

    ! splicer begin namespace.eigen.module_top
    ! splicer end namespace.eigen.module_top

    interface

        function c_init_eigen_decomp_d(rows, cols, layers, dx, dy, dz, &
                uniformDeltaX, uniformDeltaY, uniformDeltaZ, &
                leftIsNeumann, rightIsNeumann, topIsNeumann, &
                bottomIsNeumann, backIsNeumann, frontIsNeumann, leftVal, &
                rightVal, topVal, bottomVal, frontVal, backVal, &
                isStaggered, thomas) &
                result(SHT_rv) &
                bind(C, name="EIG_eigen_initEigenDecomp_d")
            use iso_c_binding, only : C_BOOL, C_DOUBLE, C_SIZE_T
            implicit none
            integer(C_SIZE_T), value, intent(IN) :: rows
            integer(C_SIZE_T), value, intent(IN) :: cols
            integer(C_SIZE_T), value, intent(IN) :: layers
            real(C_DOUBLE), intent(IN) :: dx(*)
            real(C_DOUBLE), intent(IN) :: dy(*)
            real(C_DOUBLE), intent(IN) :: dz(*)
            logical(C_BOOL), value, intent(IN) :: uniformDeltaX
            logical(C_BOOL), value, intent(IN) :: uniformDeltaY
            logical(C_BOOL), value, intent(IN) :: uniformDeltaZ
            logical(C_BOOL), value, intent(IN) :: leftIsNeumann
            logical(C_BOOL), value, intent(IN) :: rightIsNeumann
            logical(C_BOOL), value, intent(IN) :: topIsNeumann
            logical(C_BOOL), value, intent(IN) :: bottomIsNeumann
            logical(C_BOOL), value, intent(IN) :: backIsNeumann
            logical(C_BOOL), value, intent(IN) :: frontIsNeumann
            real(C_DOUBLE), value, intent(IN) :: leftVal
            real(C_DOUBLE), value, intent(IN) :: rightVal
            real(C_DOUBLE), value, intent(IN) :: topVal
            real(C_DOUBLE), value, intent(IN) :: bottomVal
            real(C_DOUBLE), value, intent(IN) :: frontVal
            real(C_DOUBLE), value, intent(IN) :: backVal
            logical(C_BOOL), value, intent(IN) :: isStaggered
            logical(C_BOOL), value, intent(IN) :: thomas
            integer(C_SIZE_T) :: SHT_rv
        end function c_init_eigen_decomp_d

        function c_init_eigen_decomp_s(rows, cols, layers, dx, dy, dz, &
                uniformDeltaX, uniformDeltaY, uniformDeltaZ, &
                leftIsNeumann, rightIsNeumann, topIsNeumann, &
                bottomIsNeumann, backIsNeumann, frontIsNeumann, leftVal, &
                rightVal, topVal, bottomVal, frontVal, backVal, &
                isStaggered, thomas) &
                result(SHT_rv) &
                bind(C, name="EIG_eigen_initEigenDecomp_s")
            use iso_c_binding, only : C_BOOL, C_FLOAT, C_SIZE_T
            implicit none
            integer(C_SIZE_T), value, intent(IN) :: rows
            integer(C_SIZE_T), value, intent(IN) :: cols
            integer(C_SIZE_T), value, intent(IN) :: layers
            real(C_FLOAT), intent(IN) :: dx(*)
            real(C_FLOAT), intent(IN) :: dy(*)
            real(C_FLOAT), intent(IN) :: dz(*)
            logical(C_BOOL), value, intent(IN) :: uniformDeltaX
            logical(C_BOOL), value, intent(IN) :: uniformDeltaY
            logical(C_BOOL), value, intent(IN) :: uniformDeltaZ
            logical(C_BOOL), value, intent(IN) :: leftIsNeumann
            logical(C_BOOL), value, intent(IN) :: rightIsNeumann
            logical(C_BOOL), value, intent(IN) :: topIsNeumann
            logical(C_BOOL), value, intent(IN) :: bottomIsNeumann
            logical(C_BOOL), value, intent(IN) :: backIsNeumann
            logical(C_BOOL), value, intent(IN) :: frontIsNeumann
            real(C_FLOAT), value, intent(IN) :: leftVal
            real(C_FLOAT), value, intent(IN) :: rightVal
            real(C_FLOAT), value, intent(IN) :: topVal
            real(C_FLOAT), value, intent(IN) :: bottomVal
            real(C_FLOAT), value, intent(IN) :: frontVal
            real(C_FLOAT), value, intent(IN) :: backVal
            logical(C_BOOL), value, intent(IN) :: isStaggered
            logical(C_BOOL), value, intent(IN) :: thomas
            integer(C_SIZE_T) :: SHT_rv
        end function c_init_eigen_decomp_s

        subroutine solve_eigen_decomp_d(solverHandle, x, b) &
                bind(C, name="EIG_eigen_solveEigenDecomp_d")
            use iso_c_binding, only : C_DOUBLE, C_SIZE_T
            implicit none
            integer(C_SIZE_T), value, intent(IN) :: solverHandle
            real(C_DOUBLE), intent(OUT) :: x(*)
            real(C_DOUBLE), intent(IN) :: b(*)
        end subroutine solve_eigen_decomp_d

        subroutine solve_eigen_decomp_s(solverHandle, x, b) &
                bind(C, name="EIG_eigen_solveEigenDecomp_s")
            use iso_c_binding, only : C_FLOAT, C_SIZE_T
            implicit none
            integer(C_SIZE_T), value, intent(IN) :: solverHandle
            real(C_FLOAT), intent(OUT) :: x(*)
            real(C_FLOAT), intent(IN) :: b(*)
        end subroutine solve_eigen_decomp_s

        subroutine finalize_eigen_decomp_d() &
                bind(C, name="EIG_eigen_finalizeEigenDecomp_d")
            implicit none
        end subroutine finalize_eigen_decomp_d

        subroutine finalize_eigen_decomp_s() &
                bind(C, name="EIG_eigen_finalizeEigenDecomp_s")
            implicit none
        end subroutine finalize_eigen_decomp_s
    end interface

    ! splicer begin namespace.eigen.additional_declarations
    ! splicer end namespace.eigen.additional_declarations

contains

    function init_eigen_decomp_d(rows, cols, layers, dx, dy, dz, &
            uniformDeltaX, uniformDeltaY, uniformDeltaZ, leftIsNeumann, &
            rightIsNeumann, topIsNeumann, bottomIsNeumann, &
            backIsNeumann, frontIsNeumann, leftVal, rightVal, topVal, &
            bottomVal, frontVal, backVal, isStaggered, thomas) &
            result(SHT_rv)
        use iso_c_binding, only : C_BOOL, C_DOUBLE, C_SIZE_T
        integer(C_SIZE_T), value, intent(IN) :: rows
        integer(C_SIZE_T), value, intent(IN) :: cols
        integer(C_SIZE_T), value, intent(IN) :: layers
        real(C_DOUBLE), intent(IN) :: dx(:)
        real(C_DOUBLE), intent(IN) :: dy(:)
        real(C_DOUBLE), intent(IN) :: dz(:)
        logical, value, intent(IN) :: uniformDeltaX
        logical, value, intent(IN) :: uniformDeltaY
        logical, value, intent(IN) :: uniformDeltaZ
        logical, value, intent(IN) :: leftIsNeumann
        logical, value, intent(IN) :: rightIsNeumann
        logical, value, intent(IN) :: topIsNeumann
        logical, value, intent(IN) :: bottomIsNeumann
        logical, value, intent(IN) :: backIsNeumann
        logical, value, intent(IN) :: frontIsNeumann
        real(C_DOUBLE), value, intent(IN) :: leftVal
        real(C_DOUBLE), value, intent(IN) :: rightVal
        real(C_DOUBLE), value, intent(IN) :: topVal
        real(C_DOUBLE), value, intent(IN) :: bottomVal
        real(C_DOUBLE), value, intent(IN) :: frontVal
        real(C_DOUBLE), value, intent(IN) :: backVal
        logical, value, intent(IN) :: isStaggered
        logical, value, intent(IN) :: thomas
        integer(C_SIZE_T) :: SHT_rv
        ! splicer begin namespace.eigen.function.init_eigen_decomp_d
        logical(C_BOOL) :: SHT_uniformDeltaX_cxx
        logical(C_BOOL) :: SHT_uniformDeltaY_cxx
        logical(C_BOOL) :: SHT_uniformDeltaZ_cxx
        logical(C_BOOL) :: SHT_leftIsNeumann_cxx
        logical(C_BOOL) :: SHT_rightIsNeumann_cxx
        logical(C_BOOL) :: SHT_topIsNeumann_cxx
        logical(C_BOOL) :: SHT_bottomIsNeumann_cxx
        logical(C_BOOL) :: SHT_backIsNeumann_cxx
        logical(C_BOOL) :: SHT_frontIsNeumann_cxx
        logical(C_BOOL) :: SHT_isStaggered_cxx
        logical(C_BOOL) :: SHT_thomas_cxx
        SHT_uniformDeltaX_cxx = uniformDeltaX  ! coerce to C_BOOL
        SHT_uniformDeltaY_cxx = uniformDeltaY  ! coerce to C_BOOL
        SHT_uniformDeltaZ_cxx = uniformDeltaZ  ! coerce to C_BOOL
        SHT_leftIsNeumann_cxx = leftIsNeumann  ! coerce to C_BOOL
        SHT_rightIsNeumann_cxx = rightIsNeumann  ! coerce to C_BOOL
        SHT_topIsNeumann_cxx = topIsNeumann  ! coerce to C_BOOL
        SHT_bottomIsNeumann_cxx = bottomIsNeumann  ! coerce to C_BOOL
        SHT_backIsNeumann_cxx = backIsNeumann  ! coerce to C_BOOL
        SHT_frontIsNeumann_cxx = frontIsNeumann  ! coerce to C_BOOL
        SHT_isStaggered_cxx = isStaggered  ! coerce to C_BOOL
        SHT_thomas_cxx = thomas  ! coerce to C_BOOL
        SHT_rv = c_init_eigen_decomp_d(rows, cols, layers, dx, dy, dz, &
            SHT_uniformDeltaX_cxx, SHT_uniformDeltaY_cxx, &
            SHT_uniformDeltaZ_cxx, SHT_leftIsNeumann_cxx, &
            SHT_rightIsNeumann_cxx, SHT_topIsNeumann_cxx, &
            SHT_bottomIsNeumann_cxx, SHT_backIsNeumann_cxx, &
            SHT_frontIsNeumann_cxx, leftVal, rightVal, topVal, &
            bottomVal, frontVal, backVal, SHT_isStaggered_cxx, &
            SHT_thomas_cxx)
        ! splicer end namespace.eigen.function.init_eigen_decomp_d
    end function init_eigen_decomp_d

    function init_eigen_decomp_s(rows, cols, layers, dx, dy, dz, &
            uniformDeltaX, uniformDeltaY, uniformDeltaZ, leftIsNeumann, &
            rightIsNeumann, topIsNeumann, bottomIsNeumann, &
            backIsNeumann, frontIsNeumann, leftVal, rightVal, topVal, &
            bottomVal, frontVal, backVal, isStaggered, thomas) &
            result(SHT_rv)
        use iso_c_binding, only : C_BOOL, C_FLOAT, C_SIZE_T
        integer(C_SIZE_T), value, intent(IN) :: rows
        integer(C_SIZE_T), value, intent(IN) :: cols
        integer(C_SIZE_T), value, intent(IN) :: layers
        real(C_FLOAT), intent(IN) :: dx(:)
        real(C_FLOAT), intent(IN) :: dy(:)
        real(C_FLOAT), intent(IN) :: dz(:)
        logical, value, intent(IN) :: uniformDeltaX
        logical, value, intent(IN) :: uniformDeltaY
        logical, value, intent(IN) :: uniformDeltaZ
        logical, value, intent(IN) :: leftIsNeumann
        logical, value, intent(IN) :: rightIsNeumann
        logical, value, intent(IN) :: topIsNeumann
        logical, value, intent(IN) :: bottomIsNeumann
        logical, value, intent(IN) :: backIsNeumann
        logical, value, intent(IN) :: frontIsNeumann
        real(C_FLOAT), value, intent(IN) :: leftVal
        real(C_FLOAT), value, intent(IN) :: rightVal
        real(C_FLOAT), value, intent(IN) :: topVal
        real(C_FLOAT), value, intent(IN) :: bottomVal
        real(C_FLOAT), value, intent(IN) :: frontVal
        real(C_FLOAT), value, intent(IN) :: backVal
        logical, value, intent(IN) :: isStaggered
        logical, value, intent(IN) :: thomas
        integer(C_SIZE_T) :: SHT_rv
        ! splicer begin namespace.eigen.function.init_eigen_decomp_s
        logical(C_BOOL) :: SHT_uniformDeltaX_cxx
        logical(C_BOOL) :: SHT_uniformDeltaY_cxx
        logical(C_BOOL) :: SHT_uniformDeltaZ_cxx
        logical(C_BOOL) :: SHT_leftIsNeumann_cxx
        logical(C_BOOL) :: SHT_rightIsNeumann_cxx
        logical(C_BOOL) :: SHT_topIsNeumann_cxx
        logical(C_BOOL) :: SHT_bottomIsNeumann_cxx
        logical(C_BOOL) :: SHT_backIsNeumann_cxx
        logical(C_BOOL) :: SHT_frontIsNeumann_cxx
        logical(C_BOOL) :: SHT_isStaggered_cxx
        logical(C_BOOL) :: SHT_thomas_cxx
        SHT_uniformDeltaX_cxx = uniformDeltaX  ! coerce to C_BOOL
        SHT_uniformDeltaY_cxx = uniformDeltaY  ! coerce to C_BOOL
        SHT_uniformDeltaZ_cxx = uniformDeltaZ  ! coerce to C_BOOL
        SHT_leftIsNeumann_cxx = leftIsNeumann  ! coerce to C_BOOL
        SHT_rightIsNeumann_cxx = rightIsNeumann  ! coerce to C_BOOL
        SHT_topIsNeumann_cxx = topIsNeumann  ! coerce to C_BOOL
        SHT_bottomIsNeumann_cxx = bottomIsNeumann  ! coerce to C_BOOL
        SHT_backIsNeumann_cxx = backIsNeumann  ! coerce to C_BOOL
        SHT_frontIsNeumann_cxx = frontIsNeumann  ! coerce to C_BOOL
        SHT_isStaggered_cxx = isStaggered  ! coerce to C_BOOL
        SHT_thomas_cxx = thomas  ! coerce to C_BOOL
        SHT_rv = c_init_eigen_decomp_s(rows, cols, layers, dx, dy, dz, &
            SHT_uniformDeltaX_cxx, SHT_uniformDeltaY_cxx, &
            SHT_uniformDeltaZ_cxx, SHT_leftIsNeumann_cxx, &
            SHT_rightIsNeumann_cxx, SHT_topIsNeumann_cxx, &
            SHT_bottomIsNeumann_cxx, SHT_backIsNeumann_cxx, &
            SHT_frontIsNeumann_cxx, leftVal, rightVal, topVal, &
            bottomVal, frontVal, backVal, SHT_isStaggered_cxx, &
            SHT_thomas_cxx)
        ! splicer end namespace.eigen.function.init_eigen_decomp_s
    end function init_eigen_decomp_s

    ! splicer begin namespace.eigen.additional_functions
    ! splicer end namespace.eigen.additional_functions

end module eigenbcgsolver_eigen_mod
